services:
  - type: worker
    name: telegram-bot
    runtime: python
    repo: https://github.com/AnhLaConCu/Treobot/
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
